# Generated by Django 2.2.4 on 2019-08-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0005_auto_20190806_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='MID',
            fields=[
                ('mid', models.CharField(max_length=12, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lname', models.CharField(max_length=50)),
                ('tags', models.TextField()),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.MID')),
            ],
        ),
    ]
