# Generated by Django 2.2.4 on 2019-08-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0008_visitor_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event_Details',
        ),
    ]
