# Generated by Django 2.2.4 on 2019-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0011_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.DeleteModel(
            name='Event_Details',
        ),
    ]
