# Generated by Django 2.2.4 on 2019-08-08 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0012_auto_20190808_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=20)),
                ('allow_user', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.Client')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.MID')),
            ],
        ),
        migrations.CreateModel(
            name='client_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.Client')),
            ],
        ),
    ]
