# Generated by Django 2.2.4 on 2019-08-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0013_auto_20190808_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('event_id', models.CharField(blank=True, max_length=120, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='client_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
    ]
