# Generated by Django 2.2.4 on 2019-08-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0014_auto_20190808_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor_log',
            name='mid',
        ),
        migrations.AlterField(
            model_name='client_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
        migrations.DeleteModel(
            name='event_details',
        ),
        migrations.DeleteModel(
            name='Visitor_Log',
        ),
    ]
