# Generated by Django 2.2.4 on 2019-08-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0015_auto_20190808_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
        migrations.CreateModel(
            name='event_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.CharField(max_length=20)),
                ('allow_user', models.TextField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.event')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.MID')),
            ],
        ),
    ]
