# Generated by Django 2.2.4 on 2019-08-08 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagboard', '0016_auto_20190808_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
        migrations.AlterField(
            model_name='event_details',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.client'),
        ),
        migrations.CreateModel(
            name='visitor_log',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.BooleanField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.event')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagboard.MID')),
            ],
        ),
    ]
